name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-{bad,base,good,ugly} \
          gstreamer1.0-{tools,x} \
          libgirepository1.0-dev \
          libcairo2-dev \
          pkg-config \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-tools \
          gstreamer1.0-x \
          gstreamer1.0-alsa \
          gstreamer1.0-gl \
          gstreamer1.0-gtk3 \
          gstreamer1.0-qt5 \
          gstreamer1.0-pulseaudio \
          libgirepository1.0-dev \
          libcairo2-dev \
          pkg-config \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-tools \
          gstreamer1.0-x \
          gstreamer1.0-alsa \
          gstreamer1.0-gl \
          gstreamer1.0-gtk3 \
          gstreamer1.0-qt5 \
          gstreamer1.0-pulseaudio \
          libffi-dev \
          libssl-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxinerama-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxfixes-dev \
          libxss-dev \
          libxtst-dev \
          libxrandr-dev \
          libasound2-dev \
          libpulse-dev \
          libdbus-1-dev \
          libudev-dev \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-tools \
          gstreamer1.0-x \
          gstreamer1.0-alsa \
          gstreamer1.0-gl \
          gstreamer1.0-gtk3 \
          gstreamer1.0-qt5 \
          gstreamer1.0-pulseaudio
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install python-for-android
        pip install kivy[base] kivy_examples
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-platform: '33'
        sdk-build-tools: '33.0.0'
        
    - name: Initialize buildozer
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        buildozer init
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        if [ ! -d "python-for-android" ]; then
          git clone https://github.com/kivy/python-for-android.git
        fi
        cd python-for-android
        git checkout master
        cd ~/work/GitHub-Auto-Streak/GitHub-Auto-Streak
        buildozer android clean
      
    - name: Build APK
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-streak-tracker-apk
        path: bin/*.apk
        
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Git Streak Tracker APK
          
          ### What's New
          - Beautiful modern UI/UX design
          - Error-free git operations
          - Background processing for better performance
          - Real-time status updates
          - Recent log entries display
          
          ### Features
          - Track your daily coding streak
          - Automatic git repository management
          - Custom commit messages
          - Repository URL validation
          - Offline log tracking
          
          ### Installation
          1. Download the APK file
          2. Enable "Install from Unknown Sources" in your Android settings
          3. Install the APK
          4. Open the app and enter your GitHub repository URL
          5. Start tracking your coding streak!
          
          ### Requirements
          - Android 5.0 (API level 21) or higher
          - Internet connection for git operations
          - GitHub repository access
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 